name: Weekly Report
on:
  schedule:
    - cron: '43 11 * * *' # At 06:00 on Sunday
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: $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
